SET client_encoding TO 'UTF8';

-- Function used in indexes must be immutable, use immutable_to_char() instead of to_char()
CREATE OR REPLACE FUNCTION immutable_to_char(timestamp, fmt text) RETURNS text AS
$$ SELECT to_char($1, $2); $$
LANGUAGE sql immutable;

CREATE INDEX case_ccc_tran_to_ref_ct_fk_idx ON xhb_case (ccc_trans_to_ref_court_id);
CREATE INDEX xhb_case_charge_import_court ON xhb_case (charge_import_indicator, court_id, case_number);
CREATE INDEX xhb_case_committal_date_index ON xhb_case (court_id, case_type, committal_date, sent_for_trial_date, class_code);
CREATE INDEX xhb_case_court_casegrp_idx ON xhb_case (court_id, case_group_number);
CREATE INDEX xhb_case_court_case_group ON xhb_case (court_id, case_id, case_group_number);
CREATE INDEX xhb_case_court_fk ON xhb_case (court_id);
CREATE UNIQUE INDEX xhb_case_court_type_number ON xhb_case (court_id, case_type, case_number);
CREATE INDEX xhb_case_export_charges ON xhb_case (export_charges);
CREATE INDEX xhb_case_ind_change_status ON xhb_case (ind_change_status);
CREATE INDEX xhb_case_ref_court_fk ON xhb_case (ref_court_id);
CREATE INDEX xhb_case_results_verified ON xhb_case (results_verified);
CREATE UNIQUE INDEX xhb_case_unauth ON xhb_case (court_id, last_update_date, case_id);
CREATE INDEX xhb_cdf_case_listing_entry_fk ON xhb_case_diary_fixture (case_listing_entry_id);
CREATE INDEX xhb_cdf_court_site_fk ON xhb_case_diary_fixture (court_site_id);
CREATE INDEX xhb_cdf_free_txt_note_class_fk ON xhb_case_diary_fixture (free_text_note_class_id);
CREATE INDEX xhb_cdf_hearing_type_fk ON xhb_case_diary_fixture (hearing_type_id);
CREATE INDEX xhb_cdf_listing_date ON xhb_case_diary_fixture (listing_date);
CREATE INDEX xhb_cdf_list_note_pre_def_fk ON xhb_case_diary_fixture (list_note_pre_defined_id);
CREATE INDEX xhb_cdf_pre_def_note_class_fk ON xhb_case_diary_fixture (pre_def_note_class_id);
CREATE INDEX xhb_cdf_vac_pre_define_rson_fk ON xhb_case_diary_fixture (vacation_pre_defined_rson_id);
CREATE INDEX xhb_cle_case_fk ON xhb_case_listing_entry (case_id);
CREATE INDEX xhb_cle_court_fk ON xhb_case_listing_entry (court_id);
CREATE INDEX xhb_cle_court_site_fk ON xhb_case_listing_entry (court_site_id);
CREATE INDEX xhb_cle_judge_fk ON xhb_case_listing_entry (judge_id);
CREATE INDEX xhb_cle_ref_judge_type_fk ON xhb_case_listing_entry (ref_judge_type_id);
CREATE INDEX xhb_case_on_list_case_fk ON xhb_case_on_list (case_id);
CREATE INDEX xhb_case_on_list_court_room_fk ON xhb_case_on_list (court_room_id);
CREATE INDEX xhb_case_on_list_court_site_fk ON xhb_case_on_list (court_site_id);
CREATE INDEX xhb_case_on_list_crack_ine_fk ON xhb_case_on_list (cracked_ineffective_id);
CREATE INDEX xhb_case_on_list_hear_type_fk ON xhb_case_on_list (hearing_type_id);
CREATE INDEX xhb_case_on_list_list_fk ON xhb_case_on_list (list_id);
CREATE INDEX xhb_case_on_list_sitting_fk ON xhb_case_on_list (sitting_on_list_id);
CREATE INDEX xhb_case_on_list_tm_marking_fk ON xhb_case_on_list (time_marking_id);
CREATE INDEX xhb_court_address_fk ON xhb_court (address_id);
CREATE INDEX xhb_court_crst_id_crt_id ON xhb_court (crest_court_id, court_id);
CREATE INDEX xhb_court_in_service_flag ON xhb_court (in_service_flag);
CREATE UNIQUE INDEX xhb_court_short_name_idx ON xhb_court (short_name);
CREATE INDEX xhb_court_room_court_site_fk ON xhb_court_room (court_site_id, court_room_id, obs_ind);
CREATE INDEX xhb_court_room_crest_site_room ON xhb_court_room (crest_court_room_no, court_site_id, court_room_id, obs_ind);
CREATE INDEX xhb_court_room_id_crest_name ON xhb_court_room (court_room_id, court_site_id, crest_court_room_no, court_room_name);
CREATE INDEX xhb_court_room_obs_site_room ON xhb_court_room (obs_ind, court_site_id, court_room_id);
CREATE INDEX xhb_court_site_address_fk ON xhb_court_site (address_id);
CREATE INDEX xhb_court_site_court_fk ON xhb_court_site (court_id, court_site_id, court_site_code);
CREATE INDEX xhb_cpp_staging_clob ON xhb_cpp_staging_inbound (clob_id);
CREATE INDEX xhb_cpp_staging_processing ON xhb_cpp_staging_inbound (processing_status, validation_status);
CREATE INDEX xhb_cpp_staging_validation ON xhb_cpp_staging_inbound (validation_status, time_loaded, obs_ind);
CREATE INDEX xhb_hearing_case_fk ON xhb_hearing (case_id);
CREATE INDEX xhb_hearing_court_fk ON xhb_hearing (court_id, case_id, hearing_id, hearing_end_date, ref_hearing_type_id);
CREATE INDEX xhb_hearing_id_reftype_case_id ON xhb_hearing (hearing_id, ref_hearing_type_id, case_id);
CREATE INDEX xhb_hearing_linked_hearing_id ON xhb_hearing (linked_hearing_id);
CREATE INDEX xhb_hearing_ref_hearing_typ_fk ON xhb_hearing (ref_hearing_type_id);
CREATE INDEX hearingliststartdatefk ON xhb_hearing_list (court_id, start_date, list_id);
CREATE INDEX xhb_hearing_list_court_fk ON xhb_hearing_list (court_id);
CREATE INDEX xhb_list_court_fk ON xhb_list (court_id);
CREATE INDEX xhb_list_list_parent_id_fk ON xhb_list (list_parent_id);
CREATE INDEX xhb_list_list_type_fk ON xhb_list (list_type_id);
CREATE INDEX ref_court_ct_cd_crt_id_idx ON xhb_ref_court (crest_code, court_id);
CREATE INDEX xhb_ref_court_address_fk ON xhb_ref_court (address_id);
CREATE INDEX xhb_ref_court_court_fk ON xhb_ref_court (court_id);
CREATE INDEX ref_crt_rep_ccrpt_id_ct_idx ON xhb_ref_court_reporter (crest_court_reporter_id, court_id);
CREATE INDEX xhb_ref_court_reporter_crt_fk ON xhb_ref_court_reporter (court_id);
CREATE INDEX xhb_ref_crt_rep_report_firm_fk ON xhb_ref_court_reporter (ref_court_reporter_firm_id);
CREATE INDEX ref_crt_rep_ccrfid_ct_idx ON xhb_ref_court_reporter_firm (crest_court_reporter_firm_id, court_id);
CREATE INDEX xhb_ref_court_reporter_addr_fk ON xhb_ref_court_reporter_firm (address_id);
CREATE INDEX xhb_ref_court_rep_f_court_fk ON xhb_ref_court_reporter_firm (court_id);
CREATE INDEX ref_hearing_type_hc_ct_id_idx ON xhb_ref_hearing_type (hearing_type_code, court_id);
CREATE INDEX xhb_ref_hearing_type_court ON xhb_ref_hearing_type (court_id, ref_hearing_type_id, hearing_type_desc);
CREATE INDEX ref_judge_c_jud_id_ct_id_idx ON xhb_ref_judge (crest_judge_id, court_id);
CREATE INDEX xhb_ref_judge_court_fk ON xhb_ref_judge (court_id);
CREATE INDEX ref_justice_c_jp_id_ct_id_idx ON xhb_ref_justice (crest_justice_id, court_id);
CREATE INDEX xhb_ref_justice_court_fk ON xhb_ref_justice (court_id);
CREATE INDEX xhb_ref_legal_rep_court_fk ON xhb_ref_legal_representative (court_id, ref_legal_rep_id, surname);
CREATE INDEX ref_solicitor_firm_court_idx ON xhb_ref_solicitor_firm (court_id, crest_sof_id);
CREATE INDEX xhb_ref_solicitor_firm_addr_fk ON xhb_ref_solicitor_firm (address_id);
CREATE INDEX xhb_ref_solicitor_firm_crt_fk ON xhb_ref_solicitor_firm (court_id);
CREATE INDEX ref_system_code_c_t_ct_id_idx ON xhb_ref_system_code (code, code_type, court_id);
CREATE INDEX xhb_ref_system_code_court_fk ON xhb_ref_system_code (court_id, obs_ind);
CREATE INDEX xhb_ref_system_code_obs_ind ON xhb_ref_system_code (obs_ind);
CREATE INDEX xhb_sched_hear_att_ref_just ON xhb_sched_hearing_attendee (ref_justice_id);
CREATE INDEX xhb_sched_hear_att_sched_hr_fk ON xhb_sched_hearing_attendee (scheduled_hearing_id);
CREATE INDEX xhb_sch_hr_ref_crt_rep_fk ON xhb_sched_hearing_attendee (ref_court_reporter_id);
CREATE INDEX xhb_sch_hr_ref_judge_fk ON xhb_sched_hearing_attendee (ref_judge_id);
CREATE INDEX xhb_sch_hr_sh_just_fk ON xhb_sched_hearing_attendee (sh_justice_id);
CREATE INDEX xhb_sch_hr_sh_staff_fk ON xhb_sched_hearing_attendee (sh_staff_id);
CREATE INDEX xhb_sched_hear_def_sched_hr_fk ON xhb_sched_hearing_defendant (scheduled_hearing_id);
CREATE INDEX sched_hear_linked_sh_id_fk_idx ON xhb_scheduled_hearing (linked_sh_id);
CREATE INDEX sched_hear_moved_f_ct_rm_idx ON xhb_scheduled_hearing (moved_from_court_room_id);
CREATE INDEX xhb_scheduled_hearing_idx10 ON xhb_scheduled_hearing ((immutable_to_char(not_before_time,'dd-mm-yyyy')), immutable_to_char(not_before_time,'hh24:mi:ss'));
CREATE INDEX xhb_scheduled_hearing_idx9 ON xhb_scheduled_hearing (coalesce(immutable_to_char(not_before_time,'hh24:mi:ss'),'00:00:00'), immutable_to_char(original_time,'DD-MON-YYYY'));
CREATE INDEX xhb_sched_hear_hearing_fk ON xhb_scheduled_hearing (hearing_id);
CREATE INDEX xhb_sched_hear_moved ON xhb_scheduled_hearing (moved_from_court_room_id, sitting_id, hearing_id, scheduled_hearing_id, not_before_time, original_time, sequence_no);
CREATE INDEX xhb_sched_hear_sitting_fk ON xhb_scheduled_hearing (sitting_id);
CREATE INDEX xhb_sched_hear_sit_sched_seq ON xhb_scheduled_hearing (sitting_id, scheduled_hearing_id, sequence_no, not_before_time);
CREATE INDEX xhb_sched_hear_sit_seq ON xhb_scheduled_hearing (sitting_id, sequence_no);
CREATE INDEX xhb_sched_hear_starttime_idx ON xhb_scheduled_hearing (start_time, sitting_id);
CREATE INDEX xhb_sch_hear_sit_hear_sched_hr ON xhb_scheduled_hearing (sitting_id, hearing_id, scheduled_hearing_id, moved_from_court_room_id, not_before_time, original_time, sequence_no);
CREATE INDEX xhb_sh_judge_ref_judge_fk ON xhb_sh_judge (ref_judge_id);
CREATE INDEX xhb_sh_judge_sched_hear_att_fk ON xhb_sh_judge (sh_attendee_id);
CREATE INDEX xhb_justice_hearing_fk ON xhb_sh_justice (hearing_id);
CREATE INDEX xhb_sh_leg_rep_cc_info_fk ON xhb_sh_leg_rep (cc_info_id);
CREATE INDEX xhb_sh_leg_rep_ref_defence_fk ON xhb_sh_leg_rep (ref_defence_category_id);
CREATE INDEX xhb_sh_leg_rep_ref_leg_rep_fk ON xhb_sh_leg_rep (ref_legal_rep_id);
CREATE INDEX xhb_sh_leg_rep_ref_sol_firm_fk ON xhb_sh_leg_rep (ref_solicitor_firm_id);
CREATE INDEX xhb_sh_leg_rep_sched_hear_fk ON xhb_sh_leg_rep (scheduled_hearing_id);
CREATE INDEX xhb_sh_leg_rep_sch_hear_def_fk ON xhb_sh_leg_rep (sched_hear_def_id);
CREATE INDEX xhb_sitting_court_room_fk ON xhb_sitting (court_room_id);
CREATE INDEX xhb_sitting_court_site_fk ON xhb_sitting (court_site_id, sitting_id);
CREATE INDEX xhb_sitting_hearing_list_fk ON xhb_sitting (list_id);
CREATE INDEX xhb_sitting_is_float ON xhb_sitting (is_floating, list_id, court_site_id, sitting_id, court_room_id, sitting_sequence_no);
CREATE INDEX xhb_sitting_ref_judge_fk ON xhb_sitting (ref_judge_id);
CREATE INDEX xhb_sol_free_txt_note_class_fk ON xhb_sitting_on_list (free_text_note_class_id);
CREATE INDEX xhb_sol_judge_ref_fk ON xhb_sitting_on_list (judge_ref_id);
CREATE INDEX xhb_sol_listid_obsind_idx ON xhb_sitting_on_list (list_id, coalesce(obs_ind,'N'));
CREATE INDEX xhb_sol_list_fk ON xhb_sitting_on_list (list_id);
CREATE INDEX xhb_sol_list_note_pre_def_fk ON xhb_sitting_on_list (list_note_pre_defined_id);
CREATE INDEX xhb_sol_pre_def_note_class_fk ON xhb_sitting_on_list (pre_def_note_classification_id);
CREATE INDEX xhb_sol_time_marking_fk ON xhb_sitting_on_list (time_marking_id);
CREATE UNIQUE INDEX xhb_sys_audit_table_to_aud_idx ON xhb_sys_audit (table_to_audit);
CREATE INDEX formatting_blob_fk_idx ON xhb_formatting (formatted_document_blob_id);
CREATE INDEX formatting_clob_fk_idx ON xhb_formatting (xml_document_clob_id);
CREATE INDEX xhb_formatting_format_status ON xhb_formatting (format_status);
CREATE INDEX xhb_format_court_fk ON xhb_formatting (court_id);
CREATE INDEX xhb_pddamsg_time_sent_idx ON xhb_pdda_message (time_sent);
CREATE INDEX xhb_pddamsg_doc_name_idx ON xhb_pdda_message (cp_document_name, pdda_message_id);
CREATE INDEX xhb_case_xhb_case_ref_fk ON xhb_case_reference (case_id, reporting_restrictions);
CREATE INDEX xhb_configured_pub_court_rm_fk ON xhb_configured_public_notice (court_room_id);
CREATE INDEX xhb_configured_pub_pub_not_fk ON xhb_configured_public_notice (public_notice_id);
CREATE INDEX crt_lg_ent_sched_h_fk_idx ON xhb_court_log_entry (scheduled_hearing_id);
CREATE INDEX xhb_court_log_entry_case_pk ON xhb_court_log_entry (case_id);
CREATE INDEX xhb_crt_lg_ent_crt_lg_evt_d_fk ON xhb_court_log_entry (event_desc_id);
CREATE INDEX xhb_crt_log_entry_def_on_case ON xhb_court_log_entry (defendant_on_case_id);
CREATE UNIQUE INDEX xhb_court_log_event_desc_type ON xhb_court_log_event_desc (event_type);
CREATE UNIQUE INDEX cr_live_disp_court_rm_fk_idx ON xhb_cr_live_display (court_room_id);
CREATE INDEX cr_live_disp_sch_hear_fk_idx ON xhb_cr_live_display (scheduled_hearing_id);
CREATE INDEX xhb_defendant_address_fk ON xhb_defendant (address_id);
CREATE INDEX xhb_defendant_court_fk ON xhb_defendant (court_id, defendant_id, crest_defendant_id);
CREATE INDEX xhb_defendant_crid_defid ON xhb_defendant (crest_defendant_id, defendant_id);
CREATE UNIQUE INDEX xhb_def_court_id_crest_def_idx ON xhb_defendant (court_id, crest_defendant_id);
CREATE INDEX xhb_defcase_def_resv_obs_case ON xhb_defendant_on_case (defendant_id, results_verified, obs_ind, case_id);
CREATE UNIQUE INDEX xhb_defendant_case_unauth ON xhb_defendant_on_case (case_id, obs_ind, results_verified, defendant_on_case_id);
CREATE INDEX xhb_defendant_on_case_case_fk ON xhb_defendant_on_case (case_id);
CREATE INDEX xhb_defendant_on_case_defen_fk ON xhb_defendant_on_case (defendant_id);
CREATE INDEX xhb_defendant_on_case_defid ON xhb_defendant_on_case (case_id, defendant_on_case_id);
CREATE INDEX xhb_defendant_on_case_def_id ON xhb_defendant_on_case (defendant_id, case_id);
CREATE INDEX xhb_defendant_on_case_index ON xhb_defendant_on_case (case_id, custody_time_limit, results_verified);
CREATE INDEX xhb_defendant_on_cas_col_magid ON xhb_defendant_on_case (collect_magistrate_court_id);
CREATE INDEX xhb_defendant_on_cas_rel_ver ON xhb_defendant_on_case (results_verified);
CREATE INDEX xhb_display_location_id ON xhb_display (display_location_id);
CREATE INDEX xhb_display_rotation_set ON xhb_display (rotation_set_id);
CREATE INDEX xhb_display_type_id ON xhb_display (display_type_id);
CREATE INDEX xhb_public_notice_court_fk ON xhb_public_notice (court_id);
CREATE INDEX xhb_public_notice_defin_pub_fk ON xhb_public_notice (definitive_pn_id);
CREATE INDEX xhb_rotation_set_dd_doc_id ON xhb_rotation_set_dd (display_document_id);
CREATE INDEX xhb_rotation_set_dd_set_id ON xhb_rotation_set_dd (rotation_set_id);
CREATE INDEX xhb_rotation_sets_court_id ON xhb_rotation_sets (court_id);
CREATE INDEX aud_court_log_entry_i1 ON aud_court_log_entry (scheduled_hearing_id);
CREATE INDEX aud_court_log_entry_i2 ON aud_court_log_entry (defendant_on_case_id);
CREATE INDEX aud_court_log_entry_i3 ON aud_court_log_entry (case_id);
CREATE INDEX aud_cr_live_disp_i1 ON aud_cr_live_display (scheduled_hearing_id);
CREATE INDEX aud_defendant_i1 ON aud_defendant (defendant_id);
CREATE INDEX aud_defendant_on_case_i1 ON aud_defendant_on_case (case_id);
CREATE INDEX aud_defendant_on_case_pk ON aud_defendant_on_case (defendant_on_case_id);
CREATE INDEX xhb_pdda_dl_notifier_id ON xhb_pdda_dl_notifier (pdda_dl_notifier_id);
CREATE INDEX xhb_pdda_dl_notifier_idx1 ON xhb_pdda_dl_notifier (court_id, last_run_date);
CREATE INDEX aud_case_i1 ON aud_case (case_id);
CREATE INDEX aud_hearing_hearing_id ON aud_hearing (case_id, case_id);
CREATE INDEX aud_sched_hearing_attendee_1 ON aud_sched_hearing_attendee (scheduled_hearing_id);
CREATE INDEX aud_sched_hearing ON aud_scheduled_hearing (hearing_id);
